### ISSUE TITLE
SDL Error:

### ISSUE THREAD

**Issue by mj0822** [markusbuchholz/CppND-Capstone-Snake-Game#1]
I am getting this error help me to solve this error.
SDL Error : Couldn't Find matching render Driver

**Comment by markusbuchholz** [comment]
As you can see you are missing there are some issues regarding the SDL. I uses Ubuntu 18.04 and my folder is under /home/markus/SDL   (it can be the main issue) - compare the CMakeLists.txt 
I assume that you have  not installed SDL properelly yet. Please follow the instructions:; https://wiki.libsdl.org/Installation. There are of course some dependencies also. Installation of SDL is system and HW specific so it is very difficult to help remotely.

**Comment by mj0822** [comment]
Warning, configure is out of date, please re-run autogen.sh

./libtool: line 5996: cd: NEWPATH/lib: No such file or directory
libtool: link: cannot determine absolute directory name of `NEWPATH/lib'
^CMakefile:274: recipe for target 'build/SDL_hints.lo' failed
make: *** [build/SDL_hints.lo] Error 1

I followed those steps but when I did make then it starts with a warning out of date and ends with the error above.

**Comment by markusbuchholz** [comment]
Not sure what is the problem with your SDL.

You can take a look on the image how I build the project and the folder setup. I can not to push the SDL libraty since ther is a limit for 100MB. If it halps I can send you somhow SDL.zip my you shoud give me your email. After you can try to unzip in /home/your_pc/SDL and try to rerun process. It should not to be solve like this but I can do nothing more. You can type the output from the compilator in Google.



![cpp_build](https://user-images.githubusercontent.com/30973337/83354519-88c12e80-a359-11ea-9f18-5ade7e57ac63.jpg)

**Comment by mj0822** [comment]
Thank you so much Got it Now!!
solved..
